/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

fn main(){
    let mut count = 1;
    let mut sum = 0;
    while my_fib(count) < 4000000 {
        if my_fib(count) % 2 ==0 {
            sum += my_fib(count);
        }
        count += 1;
    }
    println!("{}", sum);
}

fn my_fib(terms: usize) -> u64 {
    let mut nth: u64 = 1;
    let mut m: u64 = 1;
    for i in 1..terms {
        if i == 1 {
             nth = 1;
        }
        let k = m;
        m = nth;
        nth = m+k;
    }
    nth
}
